---
vms:
  -
    name: master
    box: centos-65-x64-vbox436-nocm
    hostname: master
    forwarded_ports:
      - {guest: 80,   host: 1080}
      - {guest: 433,  host: 1433}
      - {guest: 3000, host: 3000}
    roles:
      - base
      - pe-puppet-master

  -
    name: agent1
    hostname: agent1
    box: centos-65-x64-vbox436-nocm
    synced_folders:
      - {host_path:  './puppet/graphdir/agent1',   guest_path: '/graphdir'}
    roles:
      - base
      - pe-puppet-agent-default
